import type { Metadata } from 'next'
import { Baloo_Bhai_2 as BalooBhai } from "next/font/google"
import { ReactNode } from 'react'
import { ClerkProvider } from '@clerk/nextjs'

import { ThemeProvider } from '@/components/theme_component/theme-provider'
import Navbar from '@/components/common/Navbar'
import Footer from '@/components/common/Footer'
// import "../styles/globals.css"
import "./styles/globals.css"


const devanagari = BalooBhai({
  subsets: ["latin"],
  weight: ["400", '500', '600', '700', '800']
})

type TRootLayout = {
  children: ReactNode
}


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: TRootLayout) {
  return (
    <html lang="en">
      <body className={devanagari.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
