import type { Metadata } from 'next'
import { Baloo_Bhai_2 as BalooBhai } from "next/font/google"
import { ReactNode } from 'react'

import AuthProvider from '@/components/common/AuthProvider'
import { ThemeProvider } from '@/components/theme_component/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import Navbar from '@/components/common/Navbar'
import Footer from '@/components/common/Footer'
import "./styles/globals.css"


const devanagari = BalooBhai({
  subsets: ["latin"],
  weight: ['800']
})

type TRootLayout = {
  children: ReactNode
}


export const metadata: Metadata = {
  title: 'NoteShare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: TRootLayout) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={devanagari.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
